"""Collect evaluation/results_*.json into evaluation/RESULTS.md.

    python -m tools.report
"""

import json

from tools.paths import EVAL_DIR

ORDER = ["test_clean", "test_mild", "test_medium", "test_hard", "dev_clean", "dev_medium", "all_clean", "all_medium"]
DESC = {"clean": "clean scans", "mild": "simulated photo, mild", "medium": "simulated photo, medium",
        "hard": "simulated photo, hard"}


def pct(x):
    return "—" if x is None else f"{x:.1%}"


def main():
    runs = {p.stem.removeprefix("results_"): json.loads(p.read_text()) for p in EVAL_DIR.glob("results_*.json")}
    names = [n for n in ORDER if n in runs] + sorted(n for n in runs if n not in ORDER)
    lines = [
        "# Extraction results",
        "",
        "Generated by `python -m tools.report` from `python -m tools.evaluate` runs. Ground truth: "
        "`evaluation/ground_truth.json` (read from the specimen PDF, identifiers excluded). "
        "**dev** = patients 1–7 (used while building), **test** = patients 8–10 (held out).",
        "",
        "| Run | Pages | Fields | Field accuracy | Value accuracy (written fields) | Status accuracy | "
        "Sent to review | Silent errors (KNOWN but wrong) | Page type | s/page |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for n in names:
        r, o = runs[n], runs[n]["overall"]
        split, cond = n.split("_", 1)
        lines.append(f"| {split}, {DESC.get(cond, cond)} | {r['run']['pages']} | {o['fields']} | "
                     f"{pct(o['field_accuracy'])} | {pct(o['value_accuracy_on_written'])} | "
                     f"{pct(o['status_accuracy'])} | {pct(o['review_rate_on_written'])} | "
                     f"{o['silent_errors']} ({pct(o['silent_error_rate'])}) | {pct(r['page_type_accuracy'])} | "
                     f"{r['seconds_per_page']} |")
    lines += ["", "*Field accuracy*: status right and, if something is written, value right. "
              "*Sent to review*: written fields the agent asks the midwife to confirm. "
              "*Silent errors*: fields reported KNOWN that are wrong — the agent claimed certainty and was wrong.", ""]

    for n in names:
        r = runs[n]
        lines += [f"## {n}", "", "| Page type / field kind | Fields | Field accuracy | Sent to review | Silent errors |",
                  "|---|---|---|---|---|"]
        for group in ("by_page_type", "by_kind"):
            for k, v in r[group].items():
                lines.append(f"| {k} | {v['fields']} | {pct(v['field_accuracy'])} | "
                             f"{pct(v['review_rate_on_written'])} | {v['silent_errors']} |")
        cal = r.get("calibration", {})
        if cal:
            lines += ["", "Confidence calibration (written text fields): "
                      + ", ".join(f"{b}: {v['accuracy']:.0%} of {v['n']}" for b, v in cal.items()), ""]
    (EVAL_DIR / "RESULTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines[:len(names) + 7]))


if __name__ == "__main__":
    main()
